name: pytest

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 3
      matrix:
        python-version: [3.8, 3.9]

    steps:
    - uses: actions/checkout@v1
    - name: Setup Conda 
      uses: conda-incubator/setup-miniconda@v2
      with:
          python-version: ${{ matrix.python-version }}
          auto-update-conda: true
    - name: Install dependencies and package
      shell: bash --login {0}
      run: |
        conda info
        python -m pip install --upgrade pip
        pip install .[tf-cpu]
        # Install LHAPDF
        conda install -y lhapdf -c https://packages.nnpdf.science/conda
        # Download and install a PDF set to ensure that the environment paths are working
        wget http://pcteserver.mi.infn.it/~nnpdf/nnpdf31/NNPDF31_nnlo_as_0118.tar.gz
        mkdir -p pdfsets
        tar xvfz NNPDF31_nnlo_as_0118.tar.gz
        mv NNPDF31_nnlo_as_0118 pdfsets/
    - name: Test with pytest
      shell: bash --login {0}
      run: |
        # Download the PDF set
        export PDFFLOW_DATA_PATH="pdfsets"
        pip install pytest
        pytest
